CREATE TABLE IF NOT EXISTS dm_player_chats (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 campaign_id BIGINT UNSIGNED NOT NULL,
 player_id BIGINT UNSIGNED NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE(campaign_id,player_id),
 FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE,
 FOREIGN KEY (player_id) REFERENCES users(id) ON DELETE CASCADE,
 INDEX(campaign_id,updated_at)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS dm_player_chat_messages (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 chat_id BIGINT UNSIGNED NOT NULL,
 sender_id BIGINT UNSIGNED NOT NULL,
 message TEXT NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 read_by_dm BOOLEAN NOT NULL DEFAULT FALSE,
 read_by_player BOOLEAN NOT NULL DEFAULT FALSE,
 FOREIGN KEY (chat_id) REFERENCES dm_player_chats(id) ON DELETE CASCADE,
 FOREIGN KEY (sender_id) REFERENCES users(id) ON DELETE CASCADE,
 INDEX(chat_id,id),
 INDEX(sender_id,created_at)
) ENGINE=InnoDB;
