CREATE TABLE IF NOT EXISTS scenario_map_focus (
 scenario_id BIGINT UNSIGNED PRIMARY KEY,
 x INT UNSIGNED NOT NULL,
 y INT UNSIGNED NOT NULL,
 width_cells INT UNSIGNED NOT NULL,
 height_cells INT UNSIGNED NOT NULL,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY (scenario_id) REFERENCES scenarios(id) ON DELETE CASCADE
) ENGINE=InnoDB;
